# Generated by Django 2.0.4 on 2018-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
