# Generated by Django 2.0.4 on 2018-04-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='User',
        ),
    ]
